CREATE TABLE IF NOT EXISTS photographer (
  `id` BIGINT(18) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  `contact` VARCHAR(128) NULL,
  `link_portifolio` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;